### ISSUE TITLE
export 504 Gateway Time-out

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#1165]
### Discussed in https://github.com/EcrituresNumeriques/stylo/discussions/1164

<div type='discussions-op-text'>

<sup>Originally posted by **Pixflowave** December 13, 2024</sup>
Bonsoir,
je n'ai pas réussi à faire d'export .pdf ou .odt . Je n'ai réussi qu'a obtenir une version html incompléte ...</div>

```bash
[2024-12-16 08:17:46,347] ERROR in app: Exception on /generique/export/stylo.huma-num.fr/5ced91acdac870001970e5d4/how-to-stylo/ [GET]
Traceback (most recent call last):
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/styloexport/views.py", line 240, in export
    article = get_article(
              ^^^^^^^^^^^^
  File "/usr/stylo-export/styloexport/views.py", line 121, in get_article
    article.fetch_all(templates_folder, force=force_download)
  File "/usr/stylo-export/styloexport/article.py", line 292, in fetch_all
    self.download_images(templates_folder, force=force)
  File "/usr/stylo-export/styloexport/article.py", line 39, in bail_on_errors
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/styloexport/article.py", line 186, in download_images
    image_path = self._download_image(image, images_path, force)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/styloexport/article.py", line 250, in _download_image
    response = client.get(image_url, follow_redirects=True, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
           ^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 99] Cannot assign requested address
```

J'ai une autre erreur dans un autre article : 

```
[2024-12-16 08:27:39,149] ERROR in app: Exception on /generique/export/stylo.huma-num.fr/61b202628eded40012f59a3c/article-long-issue-502/ [GET]
Traceback (most recent call last):
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/styloexport/views.py", line 240, in export
    article = get_article(
              ^^^^^^^^^^^^
  File "/usr/stylo-export/styloexport/views.py", line 121, in get_article
    article.fetch_all(templates_folder, force=force_download)
  File "/usr/stylo-export/styloexport/article.py", line 290, in fetch_all
    self.extract_metadata()
  File "/usr/stylo-export/styloexport/article.py", line 39, in bail_on_errors
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/stylo-export/styloexport/article.py", line 152, in extract_metadata
    if abstract["lang"] == "fr":
       ~~~~~~~~^^^^^^^^
KeyError: 'lang'
```

**Comment by thom4parisot** [comment]
@davidbgk je suis preneur d'aide sur ces bugs. J'ai ajouté les articles en question dans le workspace `stylo-export-test` ; j'ai test qu'en faisant l'export au format ODT. Tu saurais dire ce qui coince à l'aide des logs ci-dessus ?

**Comment by davidbgk** [comment]
La première erreur concerne une image qui n'arrive pas à être récupérée… mais il ne semble pas y avoir d'images dans ces articles 🤔 

La seconde erreur c'est parce que la clé `abstract` du yaml ne contient pas la langue, je m'attends à une structure du type:

```yaml
abstract:
  - lang: fr
    text: >-
      C'est article est un exemple d'article type édité sur Stylo. Stylo est un
      éditeur d'article scientifique dédié aux sciences humaines. […]
``` 

Et là on a:

```yaml
abstract: >-
  On entend parfois des mots lourds de préjugés sur la maladie mentale, au
  détour d’une publicité, d’un film ou d’un magazine. On parle de « folie, de
  dérangés, de fuckés et d’anormaux ». Malgré un progrès notable dans les
  dernières années, les troubles de santé mentale sont encore stigmatisés. […]
```

Note que dans mon code j'ai [un commentaire en TODO](https://gitlab.huma-num.fr/ecrinum/stylo/stylo-export/-/blob/main/styloexport/article.py#L151) 😅 que l'on pourrait peut-être tenter de résoudre au passage.

Je peux passer à un mode plus défensif là-dessus, en commençant par une arborescence, puis une autre en fallback, puis une langue par défaut en fallback etc. Quelles sont les pratiques d'écritures « correctes » à ce sujet ?

**Comment by thom4parisot** [comment]
@Pixflowave est-ce que tu constates encore le problème ?

**Comment by thom4parisot** [comment]
@davidbgk j'arrive toujours à reproduire le problème de mon côté : 
- :x: export HTML
- :x: export ODT
- :x: export SSG
- :x: export fichiers originaux

OK avec [la preview](https://stylo.huma-num.fr/article/5ced91acdac870001970e5d4/preview) par contre.

Avant que l'erreur soit jetée, y'avait ces lignes de débug : 

```
[2025-02-19 19:28:23,631] DEBUG in article: Saving files for article `5ced91acdac870001970e5d4`
[2025-02-19 19:28:23,632] DEBUG in article: Saved file at `/usr/stylo-export/downloads/generique/stylo-huma-num-fr/articles/how-to-stylo-5ced91acdac870001970e5d4/originals/how-to-stylo.bib`
[2025-02-19 19:28:23,633] DEBUG in article: Saved file at `/usr/stylo-export/downloads/generique/stylo-huma-num-fr/articles/how-to-stylo-5ced91acdac870001970e5d4/originals/how-to-stylo.md`
[2025-02-19 19:28:23,633] DEBUG in article: Saved file at `/usr/stylo-export/downloads/generique/stylo-huma-num-fr/articles/how-to-stylo-5ced91acdac870001970e5d4/originals/how-to-stylo.yaml`
[2025-02-19 19:28:23,633] DEBUG in article: Extracting metadata for article `5ced91acdac870001970e5d4`
[2025-02-19 19:28:23,642] DEBUG in article: Extracted metadata `{'title': 'Stylo', '@version': '1.0', 'abstract': "C'est article est un exemple d'article type édité sur Stylo. Stylo est un éditeur d'article scientifique dédié aux sciences humaines. \nVous pouvez éditer cet article pour vous entraîner. Une documentation plus complète est accessible en cliquant sur le lien documentation.", 'acknowledgements': None, 'articleslies': None, 'authors': [{'foaf': '', 'forname': 'Marcello', 'isni': '', 'orcid': '0000-0001-6424-3229', 'surname': 'Vitali-Rosati', 'viaf': '', 'wikidata': ''}, {'foaf': '', 'forname': 'Nicolas', 'isni': '', 'orcid': '0000-0001-7516-3427', 'surname': 'Sauret', 'viaf': '', 'wikidata': ''}], 'bibliography': 'SP1234.bib', 'controlledKeywords': [{'idRameau': 'FRBNF13318593', 'label': 'Édition', 'uriRameau': 'http://catalogue.bnf.fr/ark:/12148/cb13318593f'}], 'date': '2018/05/29', 'day': '29', 'dossier': [{'id': None, 'title_f': None}], 'funder': {'funder_id': None, 'funder_name': None}, 'id': None, 'id_sp': 'SP1234', 'issnnum': None, 'journal': None, 'journal_email': None, 'journal_issue': None, 'keywords': [{'lang': 'fr', 'list': 'édition, bac-à-sable', 'list_f': 'édition, bac-à-sable'}, {'lang': 'en', 'list': 'publishing, sandbox', 'list_f': 'publishing, sandbox'}], 'lang': 'fr', 'link-citations': True, 'month': '05', 'publisher': None, 'rights': None, 'subtitle': 'Un article type', 'subtitle_f': 'Un article type', 'test': 'truc', 'title_f': 'Stylo', 'translatedTitle': [{'lang': 'en', 'text_f': None}], 'translationOf': [None], 'translations': None, 'type': 'article', 'typeArticle': ['Essai'], 'url_article': None, 'year': '2018', 'nocite': '*'}`
[2025-02-19 19:28:23,642] DEBUG in article: Extracting images for article `5ced91acdac870001970e5d4`
[2025-02-19 19:28:23,642] DEBUG in article: Extracted image `('figure 3: Néguentropie : un espace de recherchecontributive du point gris de Paul KleeImage : E. Bozec,2023', 'https://do.doc.dev.pixflowave.fr/spaces/neguentropie/projects/printemps-des-cartes/3-figure.png', '')`
[2025-02-19 19:28:23,642] DEBUG in article: Extracted image `('image', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSItC97Cr7eWv_G-OAmufw7oL-pyB_zUrHk_Q&s', '')`
[2025-02-19 19:28:23,642] DEBUG in article: Extracted image `('Titre de mon image', 'https://avatars2.githubusercontent.com/u/16691667?s=200&v=4', '')`
[2025-02-19 19:28:23,642] DEBUG in article: Downloading images for article `5ced91acdac870001970e5d4`
[2025-02-19 19:28:23,642] DEBUG in article: Downloaded image `/usr/stylo-export/downloads/generique/stylo-huma-num-fr/articles/how-to-stylo-5ced91acdac870001970e5d4/images/how-to-stylo-a0b1640b20d5dea85cbfe47a1c9632d4.png`
```

**Comment by Pixflowave** [comment]
Bonjour, 
- La génération de la prévisualisation a échoué...

- 👍 md origine
- 👍 fichier md seul
- 👍 conversion docx et odt (les images ne sortent pas dans les bonnes dimensions) je ne peux pas évaluer si la mise en page est respectée. Je n'ai pas word pour vérifier la mise en page sur docx..
