### ISSUE TITLE
bug date de publication métadonnées

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#33]
lorsqu'on essaie de changer la date de publication en modifiant le champ dans le form "metadata" on a une page blanche - crash"
Le problème arrive seulement avec l'article https://stylo.ecrituresnumeriques.ca/write/5b3bdbbd3a7d4a00116410af

voici l'erreur dans la console de Chrome
```
react-dom.production.min.js:187 n {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…eriques.ca/main.f1b1ac62363edb8596fd.js:11:34076)"}mark: undefinedmessage: "unacceptable kind of an object to dump [object Undefined]"name: "YAMLException"reason: "unacceptable kind of an object to dump [object Undefined]"stack: "YAMLException: unacceptable kind of an object to dump [object Undefined]↵    at y (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:22:159846)↵    at C (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:22:158487)↵    at y (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:22:159542)↵    at Y (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:22:160439)↵    at Object.N [as safeDump] (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:22:160492)↵    at A.value (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:1:301029)↵    at updateClassInstance (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:11:19183)↵    at beginWork (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:11:21259)↵    at r (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:11:33560)↵    at c (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:11:34076)"__proto__: Error
l @ react-dom.production.min.js:187
u @ react-dom.production.min.js:184
batchedUpdates @ react-dom.production.min.js:190
w @ react-dom.production.min.js:41
Q @ react-dom.production.min.js:41
batchedUpdates @ react-dom.production.min.js:42
dispatchEvent @ react-dom.production.min.js:45
react-dom.production.min.js:185 Uncaught n {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…eriques.ca/main.f1b1ac62363edb8596fd.js:11:34076)"}mark: undefinedmessage: "unacceptable kind of an object to dump [object Undefined]"name: "YAMLException"reason: "unacceptable kind of an object to dump [object Undefined]"stack: "YAMLException: unacceptable kind of an object to dump [object Undefined]↵    at y (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:22:159846)↵    at C (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:22:158487)↵    at y (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:22:159542)↵    at Y (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:22:160439)↵    at Object.N [as safeDump] (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:22:160492)↵    at A.value (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:1:301029)↵    at updateClassInstance (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:11:19183)↵    at beginWork (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:11:21259)↵    at r (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:11:33560)↵    at c (https://stylo.ecrituresnumeriques.ca/main.f1b1ac62363edb8596fd.js:11:34076)"__proto__: Error
u @ react-dom.production.min.js:185
batchedUpdates @ react-dom.production.min.js:190
w @ react-dom.production.min.js:41
Q @ react-dom.production.min.js:41
batchedUpdates @ react-dom.production.min.js:42
dispatchEvent @ react-dom.production.min.js:45
```

**Comment by ggrossetie** [comment]
Je ferme, merci de réouvrir si le problème réapparait.
