### ISSUE TITLE
MongoError: E11000 duplicate key error collection: stylo-prod.passwords index: username_1 dup key: { username: "…" }

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#462]
Une erreur Mongo lors d'une connexion via HumanID a fait planter le service graphql (cf. #461), dont voici les logs du conteneur :

```
/authorization-code/callback - req.session.origin: https://stylo.huma-num.fr/
GET /login/openid - req.headers.referer: https://stylo.huma-num.fr/
/authorization-code/callback - callback null {
  id: '[REDACTED]',
  displayName: '[REDACTED]',
  name: { familyName: undefined, givenName: '[REDACTED]', middleName: undefined },
  _raw: '{"name":"[REDACTED]","sub":"[REDACTED]","given_name":"[REDACTED]","email":"[REDACTED]"}',
  _json: {
    name: '[REDACTED]',
    sub: '[REDACTED]',
    given_name: '[REDACTED]',
    email: '[REDACTED]'
  }
} {
  state: {
    handle: 'kM3PtrYRCxUh/rKLv4u37BqR',
    issuer: 'https://humanid.huma-num.fr',
    authorizationURL: 'https://humanid.huma-num.fr/oauth2/authorize',
    tokenURL: 'https://humanid.huma-num.fr/oauth2/token',
    userInfoURL: 'https://humanid.huma-num.fr/oauth2/userinfo',
    clientID: 'rp-stylo-hn',
    clientSecret: '[REDACTED]',
    callbackURL: 'https://stylo.huma-num.fr/authorization-code/callback',
    params: {
      response_type: 'code',
      client_id: '[REDACTED]',
      redirect_uri: 'https://stylo.huma-num.fr/authorization-code/callback',
      scope: 'openid profile email',
      state: '[REDACTED]'
    }
  }
}
/authorization-code/callback - req.session.origin: https://stylo.huma-num.fr/
/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/core/error.js:57
    return new MongoError(options);
           ^

MongoError: E11000 duplicate key error collection: stylo-prod.passwords index: username_1 dup key: { username: "[REDACTED]" }
    at Function.create (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:123:22)
    at /usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/operations/common_functions.js:265:39
    at handler (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
    at /usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/usr/src/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  driver: true,
  index: 0,
  code: 11000,
  keyPattern: { username: 1 },
  keyValue: { username: '[REDACTED]' }
}
```

**Comment by thom4parisot** [comment]
Ce bug crée un enregistrement `password` pour lequel il n'y a pas de `user` car l'enregistrement du user échoue, et ça fait planter l'application à chaque connexion.
