### ISSUE TITLE
Problème de connexion via Huma-Num

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#507]
Actuellement lorsque nous nous connectons à Stylo via Huma-Num nous obtenons une erreur "Internal Server Error".

**Comment by thom4parisot** [comment]
Les logs retournent : 

```
InternalOAuthError: failed to obtain access token
    at /usr/src/app/node_modules/passport-openidconnect/lib/strategy.js:93:38
    at /usr/src/app/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Même problème sur stylo-dev

**Comment by antoinentl** [comment]
Précision @oncletom @Mogztter : la connexion est actuellement impossible pour les utilisateurs et utilisatrices qui passent par Huma-Num.

**Comment by ggrossetie** [comment]
Il y a deux erreurs en une, la deuxième est : 

```
TypeError: req.flash is not a function
    at allFailed (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:131:15)
    at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:180:28)
    at Strategy.strategy.fail (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:302:9)
    at loaded (/usr/src/app/node_modules/passport-openidconnect/lib/strategy.js:83:21)
    at SessionStore.verify (/usr/src/app/node_modules/passport-openidconnect/lib/state/session.js:71:11)
    at Strategy.authenticate (/usr/src/app/node_modules/passport-openidconnect/lib/strategy.js:254:24)
    at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:343:9)
    at SessionStrategy.authenticate (/usr/src/app/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:366:16)
```

À noter que ce message n'est pas la cause du dysfonctionnement. Solution possible de contournement : https://stackoverflow.com/questions/34310348/passport-and-connect-flash-req-flash-is-not-a-function/42244570

La cause principale est liée au message d'erreur de Thomas ☝🏻

**Comment by ggrossetie** [comment]
L'erreur sous-jacente : 

```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

Même erreur sur stylo-dev

**Comment by ggrossetie** [comment]
Sur le même sujet, une nouvelle version "majeure" de la librairie qu'on utilise a été publié en Novembre 2021 : https://github.com/jaredhanson/passport-openidconnect

Il faudrait aussi voir si on peut attraper l'erreur pour afficher la cause. Pour l'obtenir j'ai du ajouter un `console.log` dans le code de passport 😞 
Ligne 93 de `/usr/src/app/node_modules/passport-openidconnect/lib/strategy.js` (dans le conteneur Docker):

```js
if (err) { console.log('err', err); return self.error(new InternalOAuthError('failed to obtain access token', err)); }
```

**Comment by thom4parisot** [comment]
Problème résolu, c'était lié à l'isolation de la machine pour des raisons de sécurité.
