### ISSUE TITLE
Remplacer "failureFlash: true" par un custom callback

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#509]
Actuellement nous utilisons :

```js
passport.authenticate('oidc', { failureRedirect: '/error', failureFlash: true }), async (req, res) => {})
```

Le problème est que `req.flash` a été supprimé sur Express 3.x:

```
TypeError: req.flash is not a function
    at allFailed (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:131:15)
    at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:180:28)
    at Strategy.strategy.fail (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:302:9)
    at loaded (/usr/src/app/node_modules/passport-openidconnect/lib/strategy.js:83:21)
    at SessionStore.verify (/usr/src/app/node_modules/passport-openidconnect/lib/state/session.js:71:11)
    at Strategy.authenticate (/usr/src/app/node_modules/passport-openidconnect/lib/strategy.js:254:24)
    at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:343:9)
    at SessionStrategy.authenticate (/usr/src/app/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:366:16)
```

Il est possible d'utiliser https://github.com/jaredhanson/connect-flash pour réinstaurer cette fonctionnalité mais le projet semble à l'arrêt (et je pense qu'il y avait des bonnes raisons de supprimer `req.flash`).

Je propose plutôt d'utiliser un custom callback : https://www.passportjs.org/docs/authenticate/#custom-callback qui nous permettra de choisir la meilleure stratégie afin de gérer et afficher une erreur.

_Originally posted by @Mogztter in https://github.com/EcrituresNumeriques/stylo/issues/507#issuecomment-992629257_

**Comment by ggrossetie** [comment]
Le code en question : 

https://github.com/EcrituresNumeriques/stylo/blob/e78e6a470e582f02f254ef6d8f789d19e3bdf246/graphql/app.js#L244-L264

**Comment by ggrossetie** [comment]
Il serait aussi intéressant de voir si on peut obtenir la cause d'une erreur de type `InternalOAuthError`.

Actuellement, pour l'obtenir j'ai du ajouter un `console.log` dans le code de passport 😞 
Ligne 93 de `/usr/src/app/node_modules/passport-openidconnect/lib/strategy.js` (dans le conteneur Docker):

```js
if (err) { console.log('err', err); return self.error(new InternalOAuthError('failed to obtain access token', err)); }
```
