### ISSUE TITLE
Impossible de se connecter à Stylo : message d'erreur ou erreur 502

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#594]
Depuis hier (dimanche 20 mars 2022) il n'est pas possible de se connecter à Stylo :

- connexion avec un _compte Stylo_ : message d'erreur : "Error: Email or password is incorrect"
- connexion avec un compte Huma-Num : erreur 502 sur https://stylo.huma-num.fr/login/openid

**Comment by ggrossetie** [comment]
Le serveur a crash il y a 30 heures et cette fois ça ne semble pas être une opération de maintenance.
Nous n'avons pas reçu d'alerte d'Huma Num alors qu'on a (normalement) une sonde configurée. Il faudrait les prévenir afin qu'on puisse savoir pourquoi on ne reçoit plus d'alerte.

```
$ docker ps -a
CONTAINER ID   IMAGE                 COMMAND                  CREATED      STATUS                    PORTS                      NAMES
aa940cca9735   stylo_front-stylo     "/docker-entrypoint.…"   4 days ago   Up 4 days                 127.0.0.1:3000->80/tcp     front-stylo
e3e5b700470e   stylo_graphql-stylo   "docker-entrypoint.s…"   4 days ago   Exited (1) 30 hours ago                              graphql-stylo
db42f646125b   stylo_export-stylo    "docker-entrypoint.s…"   4 days ago   Up 4 days                 127.0.0.1:3060->3060/tcp   export-stylo
ed8dcda3da3a   mongo:4.2             "docker-entrypoint.s…"   4 days ago   Up 4 days (healthy)       27017/tcp                  mongodb-stylo
```

Je suis en train d'investiguer pour connaitre la raison du crash 👀

**Comment by ggrossetie** [comment]
L'erreur qui a provoqué l'arrêt : 

```
TypeError: Cannot read properties of undefined (reading '_id')
    at Object.articles (/usr/src/app/resolvers/articleResolver.js:328:53)
    at defaultFieldResolver (/usr/src/app/node_modules/graphql/execution/execute.js:836:36)
    at resolveField (/usr/src/app/node_modules/graphql/execution/execute.js:466:18)
    at executeFields (/usr/src/app/node_modules/graphql/execution/execute.js:294:18)
    at executeOperation (/usr/src/app/node_modules/graphql/execution/execute.js:238:122)
    at executeImpl (/usr/src/app/node_modules/graphql/execution/execute.js:118:14)
    at execute (/usr/src/app/node_modules/graphql/execution/execute.js:62:35)
    at graphqlMiddleware (/usr/src/app/node_modules/express-graphql/index.js:166:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  locations: [ { line: 22, column: 5 } ],
  path: [ 'articles' ]
}
```


https://github.com/EcrituresNumeriques/stylo/blob/02a90575383635aa847c323ed9eab545e8427814/graphql/resolvers/articleResolver.js#L328


Je suppose que dans ce cas `req.user` est `undefined`.
