### ISSUE TITLE
Cannot read properties of undefined (reading 'email')

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#610]
Constaté sur stylo-dev

```
graphql-stylo    |       const email = req.user.email
graphql-stylo    |                              ^
graphql-stylo    |
graphql-stylo    | TypeError: Cannot read properties of undefined (reading 'email')
graphql-stylo    |     at /usr/src/app/app.js:207:30
graphql-stylo    |     at OAuthStrategy.strategy.success (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:219:18)
graphql-stylo    |     at verified (/usr/src/app/node_modules/passport-oauth1/lib/strategy.js:168:20)
graphql-stylo    |     at OAuthStrategy._verify (/usr/src/app/app.js:84:12)
graphql-stylo    |     at /usr/src/app/node_modules/passport-oauth1/lib/strategy.js:184:24
graphql-stylo    |     at OAuthStrategy.userProfile (/usr/src/app/node_modules/passport-oauth1/lib/strategy.js:297:10)
graphql-stylo    |     at loadIt (/usr/src/app/node_modules/passport-oauth1/lib/strategy.js:362:17)
graphql-stylo    |     at OAuthStrategy._loadUserProfile (/usr/src/app/node_modules/passport-oauth1/lib/strategy.js:377:25)
graphql-stylo    |     at destroyed (/usr/src/app/node_modules/passport-oauth1/lib/strategy.js:159:16)
graphql-stylo    |     at SessionStore.destroy (/usr/src/app/node_modules/passport-oauth1/lib/requesttoken/session.js:34:3)
graphql-stylo    |     at /usr/src/app/node_modules/passport-oauth1/lib/strategy.js:201:37
graphql-stylo    |     at /usr/src/app/node_modules/oauth/lib/oauth.js:472:12
graphql-stylo    |     at passBackControl (/usr/src/app/node_modules/oauth/lib/oauth.js:390:11)
graphql-stylo    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth.js:409:9)
graphql-stylo    |     at IncomingMessage.emit (node:events:402:35)
graphql-stylo    |     at endReadableNT (node:internal/streams/readable:1343:12)
```

**Comment by thom4parisot** [comment]
Doublon de #611

**Comment by ggrossetie** [comment]
Oups désolé je n'avais pas vu 😬
