### ISSUE TITLE
Erreur lors de l'export zip

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#617]
Apparemment il y a encore un cas où on essaie de renseigner le code de réponse HTTP alors que la réponse a déjà été envoyée au client:

```
{
  err: TypeError: Cannot read properties of undefined (reading 'date')
      at prepare (/usr/src/app/src/helpers/metadata.js:46:11)
      at exportHtml (/usr/src/app/src/export.js:73:42)
}
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:776:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:158:21)
    at errorHandler (/usr/src/app/src/export.js:141:21)
    at exportVersionZip (/usr/src/app/src/export.js:256:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

Si je ne dis pas de bêtise, cette erreur se produit sur la version 1.7.7.

**Comment by ggrossetie** [comment]
L'erreur se produit toujours.

La dernière fois qu'elle s'est produit, on a pu récupérer le log suivant : 

```
{"level":50,"time":1652196229999,"pid":20,"hostname":"72c6b4dc5bfd","cause":{},"msg":"Something went wrong!"}
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:776:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:158:21)
    at errorHandler (/usr/src/app/src/export.js:136:21)
    at exportVersionZip (/usr/src/app/src/export.js:251:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

Normalement les erreurs de Node archiver sont des `Error`: https://github.com/archiverjs/node-archiver/blob/b5cc14cc97cc64bdca32c0cbe9d660b5b979be7c/lib/error.js#L38 et pino doit correctement transformer en JSON les objets `Error` en utilisant : https://getpino.io/#/docs/api?id=serializers-object

Il faudrait ajouter des informations supplémentaire notamment le `typeof` de `err` et tenter d'obtenir la representation en chaîne de caractères.

**Comment by ggrossetie** [comment]
cela fait un moment que je ne vois plus l'erreur, je cloture.
