### ISSUE TITLE
Erreur lors de l'execution d'une requêtes GraphQL via le service d'export

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#627]
Voici la dernière log avant que le service tombe : 

```
{"level":50,"time":1652273300569,"pid":19,"hostname":"81a60fc076c1","articleId":"favicon.ico","error":{"response":{"errors":[{"message":"Cast to ObjectId failed for value \"favicon.ico\" (type string) at path \"_id\" for model \"Article\"","locations":[{"line":2,"column":5}],"path":["article"]}],"data":null,"status":500,"headers":{}},"request":{"query":"query ($articleId: ID!) {\n    article (article:$articleId) {\n      _id\n      title\n\n      workingVersion {\n        bib\n        yaml\n        md\n      }\n    }\n  }","variables":{"articleId":"favicon.ico"}}},"msg":"Something went wrong while querying article by id using GraphQL client"}
/usr/src/app/node_modules/graphql-request/dist/index.js:340
                        throw new types_1.ClientError(__assign(__assign({}, errorResult), { status: response.status, headers: response.headers }), { query: query, variables: variables });
                              ^

ClientError: Cast to ObjectId failed for value "favicon.ico" (type string) at path "_id" for model "Article": {"response":{"errors":[{"message":"Cast to ObjectId failed for value \"favicon.ico\" (type string) at path \"_id\" for model \"Article\"","locations":[{"line":2,"column":5}],"path":["article"]}],"data":null,"status":500,"headers":{}},"request":{"query":"query ($articleId: ID!) {\n    article (article:$articleId) {\n      _id\n      title\n\n      workingVersion {\n        bib\n        yaml\n        md\n      }\n    }\n  }","variables":{"articleId":"favicon.ico"}}}
    at /usr/src/app/node_modules/graphql-request/dist/index.js:340:31
    at step (/usr/src/app/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/usr/src/app/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/usr/src/app/node_modules/graphql-request/dist/index.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  response: {
    errors: [
      {
        message: 'Cast to ObjectId failed for value "favicon.ico" (type string) at path "_id" for model "Article"',
        locations: [ { line: 2, column: 5 } ],
        path: [ 'article' ]
      }
    ],
    data: null,
    status: 500,
    headers: Headers {
      [Symbol(map)]: [Object: null prototype] {
        server: [ 'nginx/1.14.0 (Ubuntu)' ],
        date: [ 'Wed, 11 May 2022 12:48:20 GMT' ],
        'content-type': [ 'application/json; charset=utf-8' ],
        'content-length': [ '195' ],
        connection: [ 'close' ],
        'x-powered-by': [ 'Express' ],
        etag: [ 'W/"c3-srUidRR834K+Iqyo5EBfHnGJxnA"' ],
        'set-cookie': [
          'connect.sid=s%3ArZgoIRX9mZwOCDn9VrTJgS0knsBEjSpm.EjjHvsR69Yb0%2FRdwNdRyOPOl4xJEKix%2BwKa1Ozdzvu4; Path=/; HttpOnly; Secure; SameSite=Lax'
        ]
      }
    }
  },
  request: {
    query: 'query ($articleId: ID!) {\n' +
      '    article (article:$articleId) {\n' +
      '      _id\n' +
      '      title\n' +
      '\n' +
      '      workingVersion {\n' +
      '        bib\n' +
      '        yaml\n' +
      '        md\n' +
      '      }\n' +
      '    }\n' +
      '  }',
    variables: { articleId: 'favicon.ico' }
  }
}
```

Si on renseigne un mauvais identifiant (comme par exemple `favicon.ico`) le service plante 😶‍🌫️

**Comment by ggrossetie** [comment]
J'aurais dis que c'était géré par défaut par Express mais apparemment ce n'est pas le cas. Quand la route est `async` il faut explicitement gérer l'exception et faire un appel à `next(error)`.

https://zellwk.com/blog/async-await-express/

J'ai ajouté une fonction qui wrap les routes dans `app.js`: https://github.com/EcrituresNumeriques/stylo/commit/23a50078d6f2499986e8d3a0bd8624c1669803cd

**Comment by thom4parisot** [comment]
Ah… ou alors migrer à Express 5: https://expressjs.com/en/guide/error-handling.html

**Comment by ggrossetie** [comment]
> Starting with Express 5, route handlers and middleware that return a Promise will call next(value) automatically when they reject or throw an error. 

Oui ça pourrait être pas mal 🙌🏻 
Par contre il n'y a pas encore de version stable, la dernière est 5.0.0-alpha.1 😞
