### ISSUE TITLE
TypeError sur le service d'export

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#634]
Dernier logs:

```
{"level":30,"time":1661344403660,"pid":19,"hostname":"2cdb6c69da69","req":{"id":5354,"method":"GET","url":"/api/v1/htmlArticle/5f3a9903aba083001985f989?preview=true","query":{"preview":"true"},"params":{},"headers":{"x-real-ip":"176.128.238.115","x-forwarded-for":"176.128.238.115","host":"stylo.ecrituresnumeriques.ca","x-nginx-proxy":"true","connection":"upgrade","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","upgrade-insecure-requests":"1","dnt":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"cross-site","sec-fetch-mode":"navigate","sec-fetch-dest":"iframe","referer":"https://stylo.huma-num.fr/","accept-encoding":"gzip, deflate, br","accept-language":"pt-BR,pt;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,fr;q=0.5,es-MX;q=0.4,es;q=0.3,it;q=0.2","if-none-match":"W/\"cb79-Ojwr8m2Yws2ftW/IlO2jasKipOI\""},"remoteAddress":"::ffff:172.18.0.1","remotePort":38602},"res":{"statusCode":304,"headers":{"x-powered-by":"Express","access-control-allow-origin":"*","etag":"W/\"cb79-Ojwr8m2Yws2ftW/IlO2jasKipOI\""}},"responseTime":366,"msg":"request completed"}
{"level":50,"time":1661347273549,"pid":19,"hostname":"2cdb6c69da69","cause":{},"typeOf":"object","causeString":"TypeError: Cannot read properties of undefined (reading 'date')","msg":"Something went wrong!"}
{"level":30,"time":1661347273551,"pid":19,"hostname":"2cdb6c69da69","req":{"id":5355,"method":"GET","url":"/api/v1/htmlArticle/630623575192f800134b350c?preview=true","query":{"preview":"true"},"params":{},"headers":{"x-real-ip":"134.59.6.4","x-forwarded-for":"134.59.6.4","host":"stylo.ecrituresnumeriques.ca","x-nginx-proxy":"true","connection":"upgrade","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","accept-language":"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3","accept-encoding":"gzip, deflate, br","referer":"https://stylo.huma-num.fr/","upgrade-insecure-requests":"1","sec-fetch-dest":"iframe","sec-fetch-mode":"navigate","sec-fetch-site":"cross-site"},"remoteAddress":"::ffff:172.18.0.1","remotePort":39522},"res":{"statusCode":500,"headers":{"x-powered-by":"Express","access-control-allow-origin":"*","content-type":"application/json; charset=utf-8","content-length":"12","etag":"W/\"c-3Rk1bge0s6VuJbi+S2m2iU0UGdY\""}},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at ServerResponse.onResFinished (/usr/src/app/node_modules/pino-http/logger.js:107:40)\n    at ServerResponse.emit (node:events:539:35)\n    at onFinish (node:_http_outgoing:830:10)\n    at callback (node:internal/streams/writable:552:21)\n    at afterWrite (node:internal/streams/writable:497:5)\n    at afterWriteTick (node:internal/streams/writable:484:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"},"responseTime":35,"msg":"request errored"}
{"level":50,"time":1661347312584,"pid":19,"hostname":"2cdb6c69da69","cause":{},"typeOf":"object","causeString":"TypeError: Cannot set properties of undefined (setting 'bibliography')","msg":"Something went wrong!"}
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:278:15)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:162:21)
    at errorHandler (/usr/src/app/src/app.js:59:26)
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:326:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
/usr/src/app/src/helpers/metadata.js:47
  if (doc.date) {
          ^

TypeError: Cannot read properties of undefined (reading 'date')
    at prepare (/usr/src/app/src/helpers/metadata.js:47:11)
    at exportHtml (/usr/src/app/src/export.js:76:38)
npm notice
npm notice New minor version of npm available! 8.5.5 -> 8.13.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.13.2>
npm notice Run `npm install -g npm@8.13.2` to update!
npm notice
```

**Comment by ggrossetie** [comment]
Même erreur hier:

```
{"level":50,"time":1663080984633,"pid":18,"hostname":"2cdb6c69da69","cause":{},"typeOf":"object","causeString":"TypeError: Cannot set properties of undefined (setting 'bibliography')","msg":"Something went wrong!"}
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:278:15)
    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:162:21)
    at errorHandler (/usr/src/app/src/app.js:59:26)
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:326:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
/usr/src/app/src/helpers/metadata.js:47
  if (doc.date) {
          ^

TypeError: Cannot read properties of undefined (reading 'date')
    at prepare (/usr/src/app/src/helpers/metadata.js:47:11)
    at exportHtml (/usr/src/app/src/export.js:76:38)
```

**Comment by ggrossetie** [comment]
Corrigé (🙏🏻) via 13bc751e5ba5310347d289f8fbae47e2fc34a4c6 et 42ead4db290d9be9f0643548d96f990fb9adeea9
