### ISSUE TITLE
Afficher un message d'erreur quand on tente d'ajouter un contact qui n'existe pas

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#650]
Actuellement, le serveur retourne une 500 et on affiche rien à l'utilisateur : 

![error](https://user-images.githubusercontent.com/333276/201361591-138e8aeb-e0bc-41d1-b57f-d69bf5669fd3.gif)

```
Something wrong happened during: Adding acquintances => 500, Internal Server Error: {"errors":[{"message":"No user found with this email","locations":[{"line":2,"column":3}],"path":["addAcquintance"]}],"data":null}
askGraphQL @ graphQL.js:35
await in askGraphQL (async)
addAcquintance @ AcquintanceService.js:135
```
```
graphQL.js:37 Uncaught (in promise) Error: No user found with this email
    at askGraphQL (graphQL.js:37:11)
    at async AcquintanceAddForm.jsx:19:5
```

**Comment by ggrossetie** [comment]
Même chose quand on essaie de s'ajouter soit même à la liste des contacts : 

```
Something wrong happened during: Adding acquintances => 500, Internal Server Error: {"errors":[{"message":"Can not add yourself to acquintance","locations":[{"line":2,"column":3}],"path":["addAcquintance"]}],"data":null}
askGraphQL @ graphQL.js:35
await in askGraphQL (async)
addAcquintance @ AcquintanceService.js:135
```

```
Uncaught (in promise) Error: Can not add yourself to acquintance
    at askGraphQL (graphQL.js:37:11)
    at async AcquintanceAddForm.jsx:19:5
```
